PackageFactory:
  Neos:
    CodeGenerator:
      packageResolution:
        defaultPackageKey: null
      patterns:

        'po:enum':
          shortDescription: >
            Creates a pseudo-enum for use in presentation objects.
          description: >
            Creates a pseudo-enum for use in presentation objects.
          arguments:
            0: A Subnamespace (relative to Vendor\Site\Presentation)
            1: The enum class name
            n: Comma-separated list of enum values
          usageExample: >
            ./flow code:generate po:enum Vendor.Site Block/Button ButtonSize xs,s,m,l,xl
          generatorClassName: >
            PackageFactory\Neos\CodeGenerator\Pattern\PresentationObjects\EnumGenerator

        'po:value':
          shortDescription: >
            Creates a presentation value object.
          description: >
            Creates a presentation value object.
          arguments:
            0: A Subnamespace (relative to Vendor\Site\Presentation)
            1: The presentation value object class name
            n: Comma-separated list of properties and corresponding types (propertyName:type)
          usageExample: >
            ./flow code:generate po:value Vendor.Site Block/Button Href value:string
          generatorClassName: >
            PackageFactory\Neos\CodeGenerator\Pattern\PresentationObjects\ValueGenerator

        'po:model':
          shortDescription: >
            Creates a presentation model.
          description: >
            Creates a presentation model.
          arguments:
            0: A Subnamespace (relative to Vendor\Site\Presentation)
            1: The presentation model class name
            n: Comma-separated list of properties and corresponding types (propertyName:type)
          usageExample: >
            ./flow code:generate po:model Vendor.Site Block/Button Button size:ButtonSize,label:string,disabled:?boolean
          generatorClassName: >
            PackageFactory\Neos\CodeGenerator\Pattern\PresentationObjects\ModelGenerator

        'po:component':
          shortDescription: >
            Creates a presentation model and component.
          description: >
            Creates a presentation model and component.
          arguments:
            0: A Subnamespace (relative to Vendor\Site\Presentation)
            1: The presentation model class name
            n: Comma-separated list of properties and corresponding types (propertyName:type)
          usageExample: >
            ./flow code:generate po:component Vendor.Site Block/Headline Headline content:string
          generatorClassName: >
            PackageFactory\Neos\CodeGenerator\Pattern\PresentationObjects\ComponentGenerator
