PackageFactory:
  Neos:
    CodeGenerator:
      shorthands:

        string:
          type: string
          example:
            presentation:
              styleguide: >
                'Lorem ipsum...'
              afx: '{{prop}}'

        lorem:
          type: string
          example:
            presentation:
              styleguide: |
                '
                    Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy
                    eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam
                    voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita
                    kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
                '
              afx: '{{prop}}'

        lorem:kitchensink:
          type: string
          example:
            presentation:
              styleguide: |
                '
                    <p>
                        Woodlands payment Osgiliath tightening. Barad-dur follow belly comforts
                        tender tough bell? Many that live deserve death. Some that die deserve
                        life. Outwitted teatime grasp defeated before stones reflection corset
                        seen animals Saruman\'s call?
                    </p>
                    <h2>
                        (H2) Tad survive ensnare joy mistake courtesy Bagshot Row.
                    </h2>
                    <p>
                        Ligulas step drops both? You shall not pass! Tender respectable success
                        Valar impressive unfriendly bloom scraped? Branch hey-diddle-diddle pony
                        trouble\'ll sleeping during jump Narsil.
                    </p>
                    <h3>
                        (H3) North valor overflowing sort Iáve mister kingly money?
                    </h3>
                    <p>
                        Curse you and all the halflings! Deserted anytime Lake-town burned caves
                        balls. Smoked lthilien forbids Thrain?
                    </p>
                    <ul>
                        <li>Adamant.</li>
                        <li>Southfarthing!</li>
                        <li>Witch-king.</li>
                        <li>Precious.</li>
                        <li>Gaffer\'s!</li>
                    </ul>
                    <ul>
                        <li>Excuse tightening yet survives two cover Undómiel city ablaze.</li>
                        <li>
                            Keepsakes deeper clouds Buckland position 21 lied bicker fountains
                            ashamed.
                        </li>
                        <li>Women rippling cold steps rules Thengel finer.</li>
                        <li>
                            Portents close Havens endured irons hundreds handle refused sister?
                        </li>
                        <li>Harbor Grubbs fellas riddles afar!</li>
                    </ul>
                    <h3>
                        (H3) Narsil enjoying shattered bigger leaderless retrieve dreamed dwarf.
                    </h3>
                    <p>
                        Ravens wonder wanted runs me crawl gaining lots faster! Khazad-dum
                        surprise baby season ranks. I bid you all a very fond farewell.
                    </p>
                    <ol>
                        <li>Narsil.</li>
                        <li>Elros.</li>
                        <li>Arwen Evenstar.</li>
                        <li>Maggot\'s?</li>
                        <li>Bagginses?</li>
                    </ol>
                    <ol>
                        <li>Concerning Hobbits l golf air fifth bell prolonging camp.</li>
                        <li>Grond humble rods nearest mangler.</li>
                        <li>Enormity Lórien merry gravy stayed move.</li>
                        <li>
                            Diversion almost notion furs between fierce laboring Nazgûl
                            ceaselessly parent.
                        </li>
                        <li>Agree ruling um wasteland Bagshot Row expect sleep.</li>
                    </ol>
                    <h3>
                        (H3) Ere answering track forests shards roof!
                    </h3>
                    <p>
                        Delay freezes Gollum. Let the Ring-bearer decide. Bagshot Row chokes pole
                        pauses immediately orders taught éored musing three-day? Disease rune
                        repel source fire Goblinses already?
                    </p>
                    <table>
                        <thead>
                            <tr>
                                <th></th>
                                <th>Dangers</th>
                                <th>Playing</th>
                                <th>Window</th>
                                <th>Meaning</th>
                                <th>Pace</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>Current</td>
                                <td>living</td>
                                <td>odds</td>
                                <td>charged</td>
                                <td>heads</td>
                                <td>felt</td>
                            </tr>
                            <tr>
                                <td>Inn</td>
                                <td>climbing</td>
                                <td>destroying</td>
                                <td>overhead</td>
                                <td>roll</td>
                                <td>mud</td>
                            </tr>
                            <tr>
                                <td>Breath</td>
                                <td>relevant</td>
                                <td>éored</td>
                                <td>hinges</td>
                                <td>year</td>
                                <td>signed</td>
                            </tr>
                            <tr>
                                <td>Accept</td>
                                <td>threads</td>
                                <td>name</td>
                                <td>fitted</td>
                                <td>precious</td>
                                <td>attacked</td>
                            </tr>
                            <tr>
                                <td>Chief</td>
                                <td>sails</td>
                                <td>first-born</td>
                                <td>pottery</td>
                                <td>lever</td>
                                <td>antagonize</td>
                            </tr>
                            <tr>
                                <td>Unoccupied</td>
                                <td>victorious</td>
                                <td>means</td>
                                <td>lovely</td>
                                <td>humble</td>
                                <td>force</td>
                            </tr>
                        </tbody>
                        <tfoot>
                            <tr>
                                <td>kinsmen</td>
                                <td>give</td>
                                <td>walking</td>
                                <td>thousand</td>
                                <td>manners</td>
                                <td>burning</td>
                            </tr>
                        </tfoot>
                    </table>
                '

        int: &int
          type: integer
          example:
            presentation:
              styleguide: '42'
              afx: '{{prop}}'
        integer: *int

        float:
          type: float
          example:
            presentation:
              styleguide: '12.34'
              afx: '{{prop}}'

        bool: &bool
          type: boolean
          example:
            presentation:
              styleguide: 'true'
              afx: >
                {{prop} ? 'true' : 'false'}
        boolean: *bool

        imagesource:
          type: \Sitegeist\Kaleidoscope\EelHelpers\ImageSourceHelperInterface
          example:
            presentation:
              styleguide: |
                Sitegeist.Kaleidoscope:DummyImageSource {
                    width = 300
                    height = 200
                }
              afx: |
                <Sitegeist.Kaleidoscope:Image
                    imageSource={{prop}}
                    srcset="@TODO: srcset"
                    sizes="@TODO: sizes"
                    />

        imagesource:hd:
          type: \Sitegeist\Kaleidoscope\EelHelpers\ImageSourceHelperInterface
          example:
            presentation:
              styleguide: |
                Sitegeist.Kaleidoscope:DummyImageSource {
                    width = 1920
                    height = 1080
                }
              afx: |
                <Sitegeist.Kaleidoscope:Image
                    imageSource={{prop}}
                    srcset="@TODO: srcset"
                    sizes="@TODO: sizes"
                    />

